# Generated by Django 2.2.12 on 2023-06-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('description', models.TextField()),
                ('img', models.CharField(max_length=256)),
                ('available_s', models.IntegerField()),
                ('available_m', models.IntegerField()),
                ('available_l', models.IntegerField()),
            ],
        ),
    ]
